package com.elysium.vanguard.core.vault

import android.content.Context
import com.google.crypto.tink.Aead
import com.google.crypto.tink.KeyTemplates
import com.google.crypto.tink.KeysetHandle
import com.google.crypto.tink.aead.AeadConfig
import com.google.crypto.tink.integration.android.AndroidKeysetManager
import java.io.File

/**
 * PHASE 2.1 — Vault master key + AEAD primitive.
 *
 * Security model:
 * - Master key generated by Tink [AES256_GCM] keyset, stored in AndroidKeysetManager
 *   (backed by SharedPreferences wrapped with Android Keystore master key — TEE-backed
 *   on devices with hardware support, software fallback otherwise).
 * - Each file gets its own random 256-bit DEK (data encryption key), generated by Tink
 *   and wrapped (encrypted) with the master AEAD. Wrapped DEK + nonce + ciphertext + tag
 *   live together in the .elyv container.
 * - Per-file DEKs mean rotating the master key is O(vault size in entries), not O(bytes),
 *   and compromised individual files don't leak the master key.
 *
 * The shared-prefs file is intentionally namespaced ("elysium_vault_keyset_prefs") so
 * it can never collide with the FTS keyset or any future Tink usage in the app.
 */
object VaultKeyManager {

    private const val KEYSET_PREF_FILE = "elysium_vault_keyset_prefs"
    private const val KEYSET_NAME = "elysium_vault_keyset"
    private const val MASTER_KEY_URI = "android-keystore://elysium_vault_master_key"

    @Volatile private var masterAead: Aead? = null

    @Synchronized
    fun getMasterAead(context: Context): Aead {
        masterAead?.let { return it }
        AeadConfig.register()
        val builder = AndroidKeysetManager.Builder()
            .withSharedPref(context, KEYSET_NAME, KEYSET_PREF_FILE)
            .withKeyTemplate(KeyTemplates.get("AES256_GCM"))
            .withMasterKeyUri(MASTER_KEY_URI)
        // AndroidKeysetManager requires a Context — use the application context via
        // the EncryptedSharedPreferences API only when falling back. In normal flow,
        // the master key URI provides Keystore-backed protection.
        val handle: KeysetHandle = builder.build().keysetHandle
        val aead = handle.getPrimitive(Aead::class.java)
        masterAead = aead
        return aead
    }

    /** Test-only helper. Drops the cached handle so a fresh one is built next call. */
    @Synchronized
    internal fun resetForTests() {
        masterAead = null
    }
}