package com.elysium.vanguard.core.runtime.distros.gui

/** Bounded virtual-desktop dimensions derived from the active Android display. */
internal data class LinuxDesktopGeometry(val width: Int, val height: Int) {
    init {
        require(width in MIN_WIDTH..MAX_WIDTH) { "desktop width is outside supported bounds" }
        require(height in MIN_HEIGHT..MAX_HEIGHT) { "desktop height is outside supported bounds" }
    }

    companion object {
        private const val MIN_WIDTH = 960
        private const val MIN_HEIGHT = 600
        private const val MAX_WIDTH = 2_560
        private const val MAX_HEIGHT = 2_560

        fun fromDisplayPixels(width: Int, height: Int): LinuxDesktopGeometry {
            require(width > 0 && height > 0) { "display dimensions must be positive" }
            return LinuxDesktopGeometry(
                width = width.coerceIn(MIN_WIDTH, MAX_WIDTH),
                height = height.coerceIn(MIN_HEIGHT, MAX_HEIGHT)
            )
        }
    }
}

/**
 * Fixed, validated process script for a real local TigerVNC desktop.
 *
 * No field is provided by a shell or network caller. The password filename is
 * generated by [VncSessionMaterial], resolution is bounded by
 * [LinuxDesktopGeometry], and TCP is hard-pinned to Android loopback.
 */
internal class LinuxDesktopLaunchPlan(
    val guestPasswordPath: String,
    val geometry: LinuxDesktopGeometry
) {
    init {
        require(GUEST_PASSWORD_PATH.matches(guestPasswordPath)) { "unsafe VNC password path" }
    }

    val script: String = """
        set -eu
        export DISPLAY=:1
        export HOME=/root
        export XDG_RUNTIME_DIR=/tmp/elysium-xdg
        mkdir -p "${'$'}XDG_RUNTIME_DIR"
        chmod 700 "${'$'}XDG_RUNTIME_DIR"
        stale_vnc_pid=${'$'}(tr -d '[:space:]' < /tmp/.X1-lock 2>/dev/null || true)
        case "${'$'}stale_vnc_pid" in
          ''|*[!0-9]*) ;;
          *) kill -0 "${'$'}stale_vnc_pid" 2>/dev/null && { echo 'another local Xvnc session already owns display :1'; exit 1; } ;;
        esac
        rm -f /tmp/.X1-lock /tmp/.X11-unix/X1
        cleanup() {
          [ -n "${'$'}{terminal_pid:-}" ] && kill "${'$'}terminal_pid" 2>/dev/null || true
          [ -n "${'$'}{window_manager_pid:-}" ] && kill "${'$'}window_manager_pid" 2>/dev/null || true
          [ -n "${'$'}{vnc_pid:-}" ] && kill "${'$'}vnc_pid" 2>/dev/null || true
        }
        trap cleanup EXIT INT TERM
        /usr/bin/Xvnc :1 -localhost -SecurityTypes VncAuth -rfbport 5901 -rfbauth $guestPasswordPath -geometry ${geometry.width}x${geometry.height} -depth 24 -AlwaysShared &
        attempt=0
        while [ ! -S /tmp/.X11-unix/X1 ] && [ "${'$'}attempt" -lt 50 ]; do
          sleep 0.1
          attempt=${'$'}((attempt + 1))
        done
        [ -S /tmp/.X11-unix/X1 ] || { echo 'Xvnc did not publish its X11 socket'; exit 1; }
        vnc_pid=${'$'}(tr -d '[:space:]' < /tmp/.X1-lock 2>/dev/null || true)
        case "${'$'}vnc_pid" in
          ''|*[!0-9]*) echo 'Xvnc did not publish a valid process id'; exit 1 ;;
        esac
        kill -0 "${'$'}vnc_pid" 2>/dev/null || { echo 'Xvnc process exited before the workspace became ready'; exit 1; }
        /usr/bin/openbox &
        window_manager_pid=${'$'}!
        /usr/bin/xterm -geometry 120x40 -fa 'DejaVu Sans Mono' -fs 14 -bg '#000000' -fg '#39ff14' -cr '#00e5ff' -title 'Elysium Linux · authenticated local workspace' &
        terminal_pid=${'$'}!
        while kill -0 "${'$'}vnc_pid" 2>/dev/null; do sleep 1; done
    """.trimIndent()

    private companion object {
        val GUEST_PASSWORD_PATH = Regex("^/run/elysium-vnc/session-[A-Za-z0-9-]+\\.passwd${'$'}")
    }
}
