package com.elysium.vanguard.core.runtime.network

/** Safe, session-scoped DNS data rendered for a guest Linux resolver. */
data class GuestDnsConfig(
    val nameservers: List<String>,
    val searchDomains: List<String> = emptyList()
) {
    init {
        require(nameservers.all(::isSafeAddress)) { "invalid nameserver" }
        require(searchDomains.all(::isSafeSearchDomain)) { "invalid search domain" }
    }

    fun renderResolvConf(): String = buildString {
        append("# Generated by Elysium for this PRoot session.\n")
        searchDomains.takeIf { it.isNotEmpty() }?.let { append("search ").append(it.joinToString(" ")).append('\n') }
        nameservers.forEach { append("nameserver ").append(it).append('\n') }
        append("options timeout:2 attempts:2\n")
    }

    companion object {
        val EMPTY = GuestDnsConfig(emptyList())

        private fun isSafeAddress(value: String): Boolean =
            value.isNotBlank() && value.length <= 253 && value.none { it.isWhitespace() || it == '#' || it == '\u0000' }

        private fun isSafeSearchDomain(value: String): Boolean =
            value.matches(Regex("[A-Za-z0-9.-]{1,253}")) && !value.startsWith('.') && !value.endsWith('.')
    }
}

/** Source of resolver data. Empty means leave the guest's DNS untouched. */
fun interface GuestDnsConfigProvider {
    fun current(): GuestDnsConfig

    companion object {
        val NONE = GuestDnsConfigProvider { GuestDnsConfig.EMPTY }
    }
}
