package com.elysium.vanguard.core.runtime.distros

import java.io.File
import java.io.IOException

class DesktopProfileInstaller(
    private val rootfsDir: File,
    private val profile: DesktopProfile,
    private val family: DistroFamily
) {

    fun install(): DesktopInstallResult {
        if (profile == DesktopProfile.TTY) {
            return DesktopInstallResult(skipped = true)
        }
        runStage("install packages") { installPackages() }
        runStage("generate VNC script") { generateVncScript() }
        runStage("generate session config") { generateSessionConfig() }
        runStage("create home skeleton") { createHomeSkeleton() }
        return DesktopInstallResult(skipped = false)
    }

    private fun installPackages() {
        if (profile.packages.isEmpty()) return
        val cmd = packageManagerCommand()
        exec(cmd)
    }

    private fun packageManagerCommand(): List<String> {
        val base = when (family) {
            DistroFamily.DEBIAN -> listOf("apt-get", "install", "-y")
            DistroFamily.MUSL -> listOf("apk", "add")
            DistroFamily.ARCH -> listOf("pacman", "-Syu", "--noconfirm")
        }
        return prootPrefix() + base + profile.packages
    }

    private fun generateVncScript() {
        val esc = "${'$'}"
        val script = """#!/system/bin/sh
# Elysium Vanguard — Desktop VNC launcher
# Auto-generated by DesktopProfileInstaller

export DISPLAY=:1
export XDG_CONFIG_HOME="${esc}HOME/.config"
export XDG_DATA_HOME="${esc}HOME/.local/share"
export XDG_CACHE_HOME="${esc}HOME/.cache"

${profile.vncCommand}
"""
        val scriptFile = File(rootfsDir, "etc/elysium/desktop.sh")
        scriptFile.parentFile?.mkdirs()
        scriptFile.writeText(script)
        scriptFile.setExecutable(true)
    }

    private fun generateSessionConfig() {
        when (profile) {
            DesktopProfile.XFCE -> generateXfceConfig()
            DesktopProfile.LXQT -> generateLxqtConfig()
            DesktopProfile.TTY -> {}
        }
    }

    private fun generateXfceConfig() {
        val xfceDir = File(rootfsDir, "root/.config/xfce4/xfconf/xfce-perchannel-xml")
        xfceDir.mkdirs()

        val displays = File(xfceDir, "displays.xml")
        displays.writeText("""<?xml version="1.0" encoding="UTF-8"?>
<channel name="displays" version="1.0">
  <property name="Default" type="empty">
    <property name="VNC" type="empty">
      <property name="ActiveProfile" type="string" value="Default"/>
      <property name="Resolution" type="string" value="1280x720"/>
      <property name="RefreshRate" type="double" value="60.0"/>
    </property>
  </property>
</channel>
""")

        val xfwm4 = File(xfceDir.parentFile?.parentFile, "xfwm4")
        xfwm4.mkdirs()
        File(xfwm4, "general.xml").writeText("""<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfwm4" version="1.0">
  <property name="general" type="empty">
    <property name="theme" type="string" value="Default"/>
    <property name="title_font" type="string" value="Sans 10"/>
    <property name="button_layout" type="string" value="O|SHMC"/>
  </property>
</channel>
""")

        val xfce4DesktopDir = File(rootfsDir, "root/.config/xfce4/desktop")
        xfce4DesktopDir.mkdirs()

        val sessionDir = File(rootfsDir, "root/.cache/sessions")
        sessionDir.mkdirs()
    }

    private fun generateLxqtConfig() {
        val lxqtDir = File(rootfsDir, "root/.config/lxqt")
        lxqtDir.mkdirs()

        File(lxqtDir, "session.conf").writeText("""[General]
desktop=lxqt-panel
windowmanager=openbox
""")

        val lxqtSettingsDir = File(rootfsDir, "root/.config/lxqt-settings")
        lxqtSettingsDir.mkdirs()
    }

    private fun createHomeSkeleton() {
        val home = File(rootfsDir, "root")
        listOf(
            ".config",
            ".local/share",
            ".cache",
            ".config/gtk-3.0",
            ".config/autostart",
            ".vnc"
        ).forEach { rel ->
            File(home, rel).mkdirs()
        }

        val vncDir = File(home, ".vnc")
        val passwdFile = File(vncDir, "passwd")
        if (!passwdFile.exists()) {
            passwdFile.writeText("")
            passwdFile.setReadable(true, true)
            passwdFile.setWritable(true, true)
        }

        File(home, ".Xauthority").let {
            if (!it.exists()) {
                it.createNewFile()
                it.setReadable(true, true)
                it.setWritable(true, true)
            }
        }

        val xstartup = File(vncDir, "xstartup")
        xstartup.writeText(vncXstartupContent())
        xstartup.setExecutable(true)

        val gtkConfig = File(home, ".config/gtk-3.0/settings.ini")
        gtkConfig.writeText("""[Settings]
gtk-theme-name=Adwaita
gtk-font-name=Sans 10
gtk-cursor-theme-name=Adwaita
""")
    }

    private fun vncXstartupContent(): String {
        val esc = "${'$'}"
        return when (profile) {
            DesktopProfile.XFCE -> """#!/system/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export DISPLAY=:1
export SHELL=/bin/sh
export XDG_CONFIG_HOME="${esc}HOME/.config"
startxfce4 &
"""
            DesktopProfile.LXQT -> """#!/system/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export DISPLAY=:1
export SHELL=/bin/sh
startlxqt &
"""
            DesktopProfile.TTY -> """#!/system/bin/sh
echo "No desktop configured"
"""
        }
    }

    private fun prootPrefix(): List<String> {
        return listOf(
            "proot",
            "--rootfs=${rootfsDir.absolutePath}",
            "-w", "/root"
        )
    }

    private fun exec(cmd: List<String>) {
        val proc = ProcessBuilder(cmd)
            .redirectErrorStream(true)
            .start()
        val exitCode = proc.waitFor()
        if (exitCode != 0) {
            val stderr = proc.inputStream.bufferedReader().readText()
            throw IOException("command exited $exitCode: ${cmd.first()}\n$stderr")
        }
    }

    private inline fun runStage(name: String, block: () -> Unit) {
        try {
            block()
        } catch (e: Exception) {
            throw IOException("desktop install failed at stage '$name': ${e.message}", e)
        }
    }
}

data class DesktopInstallResult(
    val skipped: Boolean,
    val installedPackages: List<String>? = null,
    val vncPort: Int = -1,
    val sessionType: String? = null
)
